### ISSUE TITLE
2 or more UNDEF clients cause 500 error

### ISSUE THREAD

**Issue by denibertovic** [patrickjahns/openvpn_exporter#12] opened 2020-06-04 19:43 UTC
Hi there, thanks for this tool.

I'm having some issues with parsing openvpn-status v2 logs when there are more than 1 clients listed as "UNDEF". This is the error I'm seeing:

```
An error has occurred while serving metrics:

327 error(s) occurred:
* collected metric "openvpn_bytes_received" { label:<name:"common_name" value:"UNDEF" > label:<name:"server" value:"/var/log/openvpn/openvpn-status.log" > gauge:<value:527 > } was collected before with the same name and label values
* collected metric "openvpn_bytes_sent" { label:<name:"common_name" value:"UNDEF" > label:<name:"server" value:"/var/log/openvpn/openvpn-status.log" > gauge:<value:10441 > } was collected before with the same name and label values
...
```
If there's only 1 UNDEF it's fine but if there are more than 1 it fails. It does not return any metrics just this error with the 500 response code. This in turn causes the prometheus rules to fire up thinking that openvpn is down when it's not. 

Any idea what could be causing this?

**Comment by patrickjahns** [comment] 2020-06-04 20:07
The cause of the issue is, that while collecting metrics, the prometheus golang client implementation receives two metrics with the same values for the label `common_name` (`UNDEF`) - or be a bit more precise, the labels `server` and `common_name` have the same values for two metrics.

In this case, the issue seems to be related that openvpn reports `UNDEF` as the common name for the client, when there is a connection, but the client is not yet authenticated.

Possible fix for this could be, to ignore clients with the common_name `UNDEF` in the client metrics.

Would you be able to share the status file  (anonymized) so I could take a closer look and prepare a fix ?

Btw. if you do not require the per-client metrics right now, you can disable via `--disable-client-metrics`

**Comment by patrickjahns** [comment] 2020-06-04 20:14
Thinking a little bit - we could actually also move the `UNDEF` clients into a separate metric showing how many clients are in "pending authentication" state. This metric could be used to detect issues with authentication

**Comment by denibertovic** [comment] 2020-06-05 09:36
@patrickjahns Thanks for the quick reply. Here is a minimal repro file:

```
OpenVPN CLIENT LIST
Updated,Fri Jun  5 09:03:05 2020
Common Name,Real Address,Bytes Received,Bytes Sent,Connected Since
foo_foo,::ffff:1.1.1.1,898582,674355,Thu Jun  4 08:50:24 2020
bar_bar,::ffff:2.2.2.2,1550890,1156181,Wed Jun  3 14:00:04 2020
UNDEF,::ffff:3.3.3.3,527,10441,Fri Jun  5 09:02:17 2020
UNDEF,::ffff:4.4.4.4,527,8830,Fri Jun  5 09:02:39 2020
GLOBAL STATS
Max bcast/mcast queue length,0
END
```

Like you said if I delete one UNDEF it works, but as soon as there are 2 it stops working. I wasn't aware why the UNDEFS were happening so thanks for your explanation about "pending authentication". I do have quite a lot of those on a very old VPN so it might in fact be helpful to have that as a separate metric that would serve as an indicator/alarm that something is wrong. I've noticed this happening with the other status format as well btw. I have another vpn that uses status file version 2 and it's the same result when there are multiple UNDEFS. 

I've noticed this happening when there is a large influx of new clients. In that scenario all my dashboards stop working since they indicate that the openvpn is down when in fact the exporter had just returned 500 because of this error. It makes it hard to keep an accurate count of connected clients when a large chunk of them disappear if one of the servers had only 2 UNDEFs. 

Let me know if you need me to test out anything.

**Comment by patrickjahns** [comment] 2020-06-05 15:13
Thanks for sharing, I'll prepare a fix where I'll for now ignore the `UNDEF` for client metrics. 
Need to think about how to design the metric about connections and "pending connections" a bit. Right now `openvpn_connections` would contain both authenticated and unauthenticated requests. 
I wonder if the final connections should be a `openvpn_connections + openvpn_pending_connections` or not - any thoughts from your side?

**Comment by patrickjahns** [comment] 2020-06-05 15:36
@denibertovic 
Fix is released - please let me know if this resolves your issues

**Comment by denibertovic** [comment] 2020-06-05 17:08
Hey @patrickjahns Thanks for the quick reply. I've tested the new release and it works! Yay!

> Need to think about how to design the metric about connections and "pending connections" a bit. Right now openvpn_connections would contain both authenticated and unauthenticated requests.
I wonder if the final connections should be a openvpn_connections + openvpn_pending_connections or not - any thoughts from your side?

As for your question... I think that openvpn_connections should only count the established (or to say authenticated connections) and that openvpn_pending_connections should count only the UNDEF ones. That way users can mix and match and either display openvpn_connections + openvpn_pending_connections in their dashboard or display them separately. For my use case it would definitely be useful to have openvpn_pending_connection be separate so that I can monitor fluctuations. Ideally openvpn_pending_connections should (if everything is ok) disappear (flow towards 0) in a few minutes and move over to openvpn_connections. 

An alternative would be to have openvpn_connections = openvpn_established_connections + openvpn_pending_connections. This seems to be more backwards compatible perhaps. 

Let me know what you decide and I can test it out.

**Comment by dummydata** [comment] 2020-08-05 23:09
This is also an issue if a user with the same "common name" is connected to the same server more than once. For example a home user that has connected from both their desktop and their mobile device

**Comment by dummydata** [comment] 2020-08-06 01:36
> This is also an issue if a user with the same "common name" is connected to the same server more than once. For example a home user that has connected from both their desktop and their mobile device

would this be an acceptable fix? It is working in my test setup.
https://github.com/dummydata/openvpn_exporter/commit/d19163a98a3226d15679f99a987b22356e3db7a5

**Comment by patrickjahns** [comment] 2020-08-06 11:08
@dummydata 
Your change basically skips all the client related metrics - you can achieve the same by setting `--disable-client-metrics=true` - this will skip all client based settings

For prometheus, all label (key/value) pairs must be unique per scrape iteration - the only way to change this, would be to add a additional label for the case, where two clients share the same common name.
One option would be to include the client ip, that adds another permutation - however - then we are sage as long as not two clients connect from the same public ip (i.e. natting ) - then we have the same issue again.
One could now argue to use `<publicip>:<port>` - but that will lead to a lot of permutations in the time series database 

Both of those added labels will add cardinality which might explode with 100s of clients and put a lot of stress on prometheus. So I am hesitant to add those extra labels

**Comment by dummydata** [comment] 2020-08-06 20:30
Ah, ok, that makes sense. I agree that the prospect of unbounded label growth is not a good scenario and not really a scenario worth adding features for.

In looking to move away from collectd, the OpenVPN status monitoring scenario is proving to be an interesting one as this issue appeared only after trying different exporters for OpenVPN. It appears that collectd's OpenVPN plugin is unaffected by this scenario. It must take the first entry and ignore duplicates because the number of client metrics will not match the client count when you have duplicates. This is something we hadn't noticed before.

Thanks for the quick response!

**Comment by patrickjahns** [comment] 2020-12-25 21:23
closing as original issue has been resolved

**Closed as completed by patrickjahns** 2020-12-25 21:23 UTC
Labels: bug
